name: Build all Targets

on:
  pull_request:
    branches: [ main ]
  workflow_call:
  workflow_dispatch:

jobs:
  build_all_targets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          sudo apt-get install gcc-arm-none-eabi
          sudo apt-get install ninja-build

      - name: Configure CMake
        run: cmake -B cmake-build-debug -G Ninja .

      - name: Build targets
        run: cmake --build cmake-build-debug -j 4
